---
- hosts: primary
  vars:
    site_node_gid: 2001
    site_node_group: site_node
    site_node_uid: 2001
    site_node_user: site_node
    grafana_gid: 0
    grafana_group: root
    grafana_uid: 472
    grafana_user: grafana
  tasks:
    # Required software
    - name: Install required software
      ansible.builtin.package:
        name: podman,net-tools,tcpdump,iperf3
        state: latest
    # Setup reverse SSH support
    - name: Create the site node group
      ansible.builtin.group:
        name: "{{ site_node_group }}"
        gid: "{{ site_node_gid }}"
    - name: Create the site node user
      ansible.builtin.user:
        name: "{{ site_node_user }}"
        uid: "{{ site_node_uid }}"
        group: "{{ site_node_group }}"
    - name: Set the site node user authorized key
      ansible.posix.authorized_key:
        key: "{{ site_node_ssh_key_pub }}"
        user: "{{ site_node_user }}"
    # Prometheus Server
    - name: Create Prometheus configuration path
      ansible.builtin.file:
        path: /etc/prometheus
        state: directory
        owner: root
        group: root
        mode: "0755"
    - name: Get the distribution-specific group name
      ansible.builtin.shell: "getent group 65534 | cut -d: -f1"
      register: dist_specific_group
      changed_when: false
    - name: Create Prometheus data path
      ansible.builtin.file:
        path: /var/lib/prometheus
        state: directory
        owner: nobody
        group: "{{ dist_specific_group.stdout }}"
        mode: "0755"
    - name: Create Prometheus configuration file
      ansible.builtin.template:
        src: prometheus-primary.yaml
        dest: /etc/prometheus/prometheus.yaml
        owner: root
        group: root
        mode: "0444"
      notify:
        - Restart Prometheus
    - name: Copy Prometheus systemd service unit file
      ansible.builtin.template:
        src: prometheus.service
        dest: /etc/systemd/system/prometheus.service
        owner: root
        group: root
        mode: "0444"
      notify:
        - Restart Prometheus
    - name: Install Prometheus systemd service
      ansible.builtin.systemd:
        name: prometheus
        enabled: true
        daemon_reload: true
        state: started
    # Grafana Server
    - name: Create the Grafana group
      ansible.builtin.group:
        name: "{{ grafana_group }}"
        gid: "{{ grafana_gid }}"
      when: grafana_gid > 0
    - name: Create the Grafana user
      ansible.builtin.user:
        name: "{{ grafana_user }}"
        uid: "{{ grafana_uid }}"
        group: "{{ grafana_group }}"
        home: /var/lib/grafana
        shell: /bin/false
        system: yes
    - name: Create Grafana configuration directory
      ansible.builtin.file:
        path: /etc/grafana
        state: directory
        owner: root
        group: root
        mode: "0755"
    - name: Create Grafana configuration file
      ansible.builtin.template:
        src: grafana.ini
        dest: /etc/grafana/grafana.ini
        owner: root
        group: root
        mode: "0444"
      notify:
        - Restart Grafana
    - name: Create Grafana environment file
      ansible.builtin.template:
        src: grafana.env
        dest: /etc/grafana/grafana.env
        owner: root
        group: root
        mode: "0444"
      notify:
        - Restart Grafana
    - name: Copy Grafana systemd service unit file
      ansible.builtin.template:
        src: grafana.service
        dest: /etc/systemd/system/grafana.service
        owner: root
        group: root
        mode: "0444"
      notify:
        - Restart Grafana
    - name: Install Grafana systemd service
      ansible.builtin.systemd:
        name: grafana
        enabled: true
        daemon_reload: true
        state: started
    # Firewall config assumes upstream NACLs
    - name: Open Prometheus port
      ansible.posix.firewalld:
        port: 9090/tcp
        permanent: yes
        state: enabled
    - name: Open Grafana port
      ansible.posix.firewalld:
        port: 3000/tcp
        permanent: yes
        state: enabled
  handlers:
    - name: Restart Prometheus
      ansible.builtin.systemd:
        name: prometheus
        state: restarted
        daemon_reload: true
    - name: Restart Grafana
      ansible.builtin.systemd:
        name: grafana
        state: restarted
        daemon_reload: true
