global:
  scrape_interval: 15s
  external_labels:
    monitor: "{{ site_node_name }}"
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
        - localhost:9090
  - job_name: speedtest
    scrape_interval: 5m
    scrape_timeout: 2m
    metrics_path: /probe
    static_configs:
      - targets:
        - localhost:9516
  - job_name: smokeping
    metrics_path: /metrics
    static_configs:
      - targets:
        - localhost:9374
